version: "3.0"

# Services to run
services:
  mongo_strategy: # name of BD service
    image: mongo
    container_name: mongo_db_auth_handslab_roles
    ports:
      - 27017:27017
    volumes:
      - mongoauthhandslabroles:/data/configdb
      - mongoauthhandslabroles:/data/db
    # restart: always

volumes:
  mongoauthhandslabroles:
