version: "3.0"

# Services to run
services:
  mongo_jwt: # name of BD service
    image: mongo
    container_name: mongo_db_jwt
    ports:
      - 27017:27017
    volumes:
      - mongojwt:/data/configdb
      - mongojwt:/data/db
    # restart: always

volumes:
  mongojwt:
